import {
  GithubIcon,
  LinkedinIcon,
  TwitterIcon,
  GlobeIcon,
  LinkIcon,
  FacebookIcon,
  InstagramIcon,
  YoutubeIcon,
  TiktokIcon,
  ThreadsIcon,
  DiscordIcon,
  DevtoIcon,
  MediumIcon,
  RedditIcon,
  DribbbleIcon,
  BehanceIcon,
  FigmaIcon,
  StackoverflowIcon,
  NpmIcon,
  CodepenIcon,
  MastodonIcon,
  TwitchIcon,
  WhatsappIcon,
  TelegramIcon,
  EmailIcon,
} from "./icons-social";

import {
  ReactIcon,
  NextjsIcon,
  TypescriptIcon,
  JavascriptIcon,
  HtmlIcon,
  CssIcon,
  PythonIcon,
  JavaIcon,
  PhpIcon,
  LaravelIcon,
  MysqlIcon,
  PostgresqlIcon,
  MongodbIcon,
  SupabaseIcon,
  FirebaseIcon,
  RedisIcon,
  GitIcon,
  GithubIcon as GithubTechIcon,
  GitlabIcon,
  DockerIcon,
  LinuxIcon,
  WindowsIcon,
  VscodeIcon,
  VercelIcon,
  AwsIcon,
  CloudflareIcon,
  PrismaIcon,
  ExpoIcon,
  FlutterIcon,
  AndroidIcon,
  AppleIcon,
  PhotoshopIcon,
  IllustratorIcon,
  CanvaIcon,
  WordIcon,
  ExcelIcon,
  PowerpointIcon,
  OfficeIcon,
  SlackIcon,
  DiscordIcon as DiscordTechIcon,
  NotionIcon,
  TrelloIcon,
  JiraIcon,
  ZoomIcon,
  MonitorIcon,
  CpuIcon,
  WrenchIcon,
  DatabaseIcon,
  CloudIcon,
  TerminalIcon,
  CodeIcon,
  StripeIcon,
  ShopifyIcon,
  WordpressIcon,
  ChromeIcon,
  CameraIcon,
  MicrophoneIcon,
  SpeakerIcon,
  PrinterIcon,
  SettingsIcon,
} from "./icons-tech";

export type IconMeta = {
  slug: string;
  label: string;
  category: string;
  Component: React.ComponentType<{ className?: string }>;
};

export const ICONS: IconMeta[] = [
  // Social
  {
    slug: "github",
    label: "GitHub",
    category: "Social",
    Component: GithubIcon,
  },
  {
    slug: "linkedin",
    label: "LinkedIn",
    category: "Social",
    Component: LinkedinIcon,
  },
  {
    slug: "twitter",
    label: "Twitter / X",
    category: "Social",
    Component: TwitterIcon,
  },
  {
    slug: "facebook",
    label: "Facebook",
    category: "Social",
    Component: FacebookIcon,
  },
  {
    slug: "instagram",
    label: "Instagram",
    category: "Social",
    Component: InstagramIcon,
  },
  {
    slug: "youtube",
    label: "YouTube",
    category: "Social",
    Component: YoutubeIcon,
  },
  {
    slug: "tiktok",
    label: "TikTok",
    category: "Social",
    Component: TiktokIcon,
  },
  {
    slug: "threads",
    label: "Threads",
    category: "Social",
    Component: ThreadsIcon,
  },
  {
    slug: "discord",
    label: "Discord",
    category: "Social",
    Component: DiscordIcon,
  },
  { slug: "devto", label: "Dev.to", category: "Social", Component: DevtoIcon },
  {
    slug: "medium",
    label: "Medium",
    category: "Social",
    Component: MediumIcon,
  },
  {
    slug: "reddit",
    label: "Reddit",
    category: "Social",
    Component: RedditIcon,
  },
  {
    slug: "dribbble",
    label: "Dribbble",
    category: "Social",
    Component: DribbbleIcon,
  },
  {
    slug: "behance",
    label: "Behance",
    category: "Social",
    Component: BehanceIcon,
  },
  { slug: "figma", label: "Figma", category: "Social", Component: FigmaIcon },
  {
    slug: "stackoverflow",
    label: "Stack Overflow",
    category: "Social",
    Component: StackoverflowIcon,
  },
  { slug: "npm", label: "npm", category: "Social", Component: NpmIcon },
  {
    slug: "codepen",
    label: "CodePen",
    category: "Social",
    Component: CodepenIcon,
  },
  {
    slug: "mastodon",
    label: "Mastodon",
    category: "Social",
    Component: MastodonIcon,
  },
  {
    slug: "twitch",
    label: "Twitch",
    category: "Social",
    Component: TwitchIcon,
  },
  {
    slug: "whatsapp",
    label: "WhatsApp",
    category: "Social",
    Component: WhatsappIcon,
  },
  {
    slug: "telegram",
    label: "Telegram",
    category: "Social",
    Component: TelegramIcon,
  },
  { slug: "email", label: "Email", category: "Social", Component: EmailIcon },
  {
    slug: "website",
    label: "Website",
    category: "Social",
    Component: GlobeIcon,
  },
  {
    slug: "link",
    label: "Generic link",
    category: "Social",
    Component: LinkIcon,
  },

  // Languages
  {
    slug: "react",
    label: "React",
    category: "Languages",
    Component: ReactIcon,
  },
  {
    slug: "nextjs",
    label: "Next.js",
    category: "Languages",
    Component: NextjsIcon,
  },
  {
    slug: "typescript",
    label: "TypeScript",
    category: "Languages",
    Component: TypescriptIcon,
  },
  {
    slug: "javascript",
    label: "JavaScript",
    category: "Languages",
    Component: JavascriptIcon,
  },
  { slug: "html", label: "HTML", category: "Languages", Component: HtmlIcon },
  { slug: "css", label: "CSS", category: "Languages", Component: CssIcon },
  {
    slug: "python",
    label: "Python",
    category: "Languages",
    Component: PythonIcon,
  },
  { slug: "java", label: "Java", category: "Languages", Component: JavaIcon },
  { slug: "php", label: "PHP", category: "Languages", Component: PhpIcon },
  {
    slug: "laravel",
    label: "Laravel",
    category: "Languages",
    Component: LaravelIcon,
  },

  // Databases
  {
    slug: "mysql",
    label: "MySQL",
    category: "Databases",
    Component: MysqlIcon,
  },
  {
    slug: "postgresql",
    label: "PostgreSQL",
    category: "Databases",
    Component: PostgresqlIcon,
  },
  {
    slug: "mongodb",
    label: "MongoDB",
    category: "Databases",
    Component: MongodbIcon,
  },
  {
    slug: "supabase",
    label: "Supabase",
    category: "Databases",
    Component: SupabaseIcon,
  },
  {
    slug: "firebase",
    label: "Firebase",
    category: "Databases",
    Component: FirebaseIcon,
  },
  {
    slug: "redis",
    label: "Redis",
    category: "Databases",
    Component: RedisIcon,
  },

  // Tools
  { slug: "git", label: "Git", category: "Tools", Component: GitIcon },
  {
    slug: "github-tool",
    label: "GitHub (tool)",
    category: "Tools",
    Component: GithubTechIcon,
  },
  { slug: "gitlab", label: "GitLab", category: "Tools", Component: GitlabIcon },
  { slug: "docker", label: "Docker", category: "Tools", Component: DockerIcon },
  { slug: "linux", label: "Linux", category: "Tools", Component: LinuxIcon },
  {
    slug: "windows",
    label: "Windows",
    category: "Tools",
    Component: WindowsIcon,
  },
  {
    slug: "vscode",
    label: "VS Code",
    category: "Tools",
    Component: VscodeIcon,
  },
  { slug: "vercel", label: "Vercel", category: "Tools", Component: VercelIcon },
  { slug: "aws", label: "AWS", category: "Tools", Component: AwsIcon },
  {
    slug: "cloudflare",
    label: "Cloudflare",
    category: "Tools",
    Component: CloudflareIcon,
  },
  { slug: "prisma", label: "Prisma", category: "Tools", Component: PrismaIcon },
  { slug: "expo", label: "Expo", category: "Tools", Component: ExpoIcon },
  {
    slug: "flutter",
    label: "Flutter",
    category: "Tools",
    Component: FlutterIcon,
  },
  {
    slug: "android",
    label: "Android",
    category: "Tools",
    Component: AndroidIcon,
  },
  { slug: "apple", label: "Apple", category: "Tools", Component: AppleIcon },

  // Design
  {
    slug: "photoshop",
    label: "Photoshop",
    category: "Design",
    Component: PhotoshopIcon,
  },
  {
    slug: "illustrator",
    label: "Illustrator",
    category: "Design",
    Component: IllustratorIcon,
  },
  { slug: "canva", label: "Canva", category: "Design", Component: CanvaIcon },

  // Office
  { slug: "word", label: "Word", category: "Office", Component: WordIcon },
  { slug: "excel", label: "Excel", category: "Office", Component: ExcelIcon },
  {
    slug: "powerpoint",
    label: "PowerPoint",
    category: "Office",
    Component: PowerpointIcon,
  },
  {
    slug: "office",
    label: "Microsoft Office",
    category: "Office",
    Component: OfficeIcon,
  },

  // Collaboration
  {
    slug: "slack",
    label: "Slack",
    category: "Collaboration",
    Component: SlackIcon,
  },
  {
    slug: "discord-tool",
    label: "Discord (tool)",
    category: "Collaboration",
    Component: DiscordTechIcon,
  },
  {
    slug: "notion",
    label: "Notion",
    category: "Collaboration",
    Component: NotionIcon,
  },
  {
    slug: "trello",
    label: "Trello",
    category: "Collaboration",
    Component: TrelloIcon,
  },
  {
    slug: "jira",
    label: "Jira",
    category: "Collaboration",
    Component: JiraIcon,
  },
  {
    slug: "zoom",
    label: "Zoom",
    category: "Collaboration",
    Component: ZoomIcon,
  },

  // Hardware
  {
    slug: "monitor",
    label: "Monitor",
    category: "Hardware",
    Component: MonitorIcon,
  },
  { slug: "cpu", label: "CPU", category: "Hardware", Component: CpuIcon },
  {
    slug: "wrench",
    label: "Repair",
    category: "Hardware",
    Component: WrenchIcon,
  },
  {
    slug: "printer",
    label: "Printer",
    category: "Hardware",
    Component: PrinterIcon,
  },

  // Generic
  {
    slug: "database",
    label: "Database",
    category: "Generic",
    Component: DatabaseIcon,
  },
  { slug: "cloud", label: "Cloud", category: "Generic", Component: CloudIcon },
  {
    slug: "terminal",
    label: "Terminal",
    category: "Generic",
    Component: TerminalIcon,
  },
  { slug: "code", label: "Code", category: "Generic", Component: CodeIcon },
  {
    slug: "settings",
    label: "Settings",
    category: "Generic",
    Component: SettingsIcon,
  },

  // Commerce
  {
    slug: "stripe",
    label: "Stripe",
    category: "Commerce",
    Component: StripeIcon,
  },
  {
    slug: "shopify",
    label: "Shopify",
    category: "Commerce",
    Component: ShopifyIcon,
  },
  {
    slug: "wordpress",
    label: "WordPress",
    category: "Commerce",
    Component: WordpressIcon,
  },

  // Media
  { slug: "chrome", label: "Chrome", category: "Media", Component: ChromeIcon },
  { slug: "camera", label: "Camera", category: "Media", Component: CameraIcon },
  {
    slug: "microphone",
    label: "Microphone",
    category: "Media",
    Component: MicrophoneIcon,
  },
  {
    slug: "speaker",
    label: "Speaker",
    category: "Media",
    Component: SpeakerIcon,
  },
];

export function resolveIcon(slug: string) {
  return ICONS.find((i) => i.slug === slug)?.Component ?? LinkIcon;
}
